description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Raleway"
      fonts: 
        - 
          asset: "fonts/Raleway-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Raleway-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Raleway-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Raleway-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "italic"
          weight: 400
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-300.ttf"
          style: "normal"
          weight: 300
  uses-material-design: true
