import 'package:flutter/material.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedLine77Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedLine78Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratediPhoneXSBarsStatusDefaultWidget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedIconfinder_Arrow_Right_47818581Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/Generated1Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedLine79Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedOTPnotrecivedRESENDOTPWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/Generated4Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedOTPVerificationWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedEntertheOTPsentto19879878975Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/Generated2Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedLine80Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedPasswordcodeverificationsecurityprotectionauthorization.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/Generated7Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedenterotpwidget/generated/GeneratedGroup52745Widget.dart';

/* Frame Enter OTP
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEnterOTPWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.0012315270935960591,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediPhoneXSBarsStatusDefaultWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 57.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconfinder_Arrow_Right_47818581Widget(),
              ),
              Positioned(
                left: 104.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 187.0,
                child:
                    GeneratedPasswordcodeverificationsecurityprotectionauthorization(),
              ),
              Positioned(
                left: 44.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 23.0,
                child: GeneratedEntertheOTPsentto19879878975Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 1.0,
                child: GeneratedLine77Widget(),
              ),
              Positioned(
                left: 125.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 1.0,
                child: GeneratedLine78Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 1.0,
                child: GeneratedLine79Widget(),
              ),
              Positioned(
                left: 274.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 1.0,
                child: GeneratedLine80Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 31.0,
                child: Generated7Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 31.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 31.0,
                child: Generated2Widget(),
              ),
              Positioned(
                left: 290.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 31.0,
                child: Generated4Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 23.0,
                child: GeneratedOTPnotrecivedRESENDOTPWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 63.0,
                child: GeneratedGroup52745Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6026666666666667;

                  final double height =
                      constraints.maxHeight * 0.05295566502463054;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2,
                        y: constraints.maxHeight * 0.46921182266009853,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedOTPVerificationWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
