import 'package:flutter/material.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2460Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup53121Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2461Widget5.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2461Widget2.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRenovationWidget2.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2461Widget3.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRenovationWidget3.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle251Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2459Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup6942Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGardening1Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedSurface1Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedHandyman2Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle221Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle252Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedDeclutter2Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratediPhoneXSBarsStatusDefaultWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedSearch31Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2461Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGardeningWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedHomeshiftingWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup53113Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2458Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedHandymanWidget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup53093Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle222Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup53189Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedMoving1Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2461Widget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup6823Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup53112Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedPaintingWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedImageWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedGroup53182Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedDeclutterWidget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedhomewidget/generated/GeneratedRectangle2461Widget4.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 2165.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 2165.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 20.00048828125,
                                    top: 1115.281005859375,
                                    right: null,
                                    bottom: null,
                                    width: 335.0,
                                    height: 373.0,
                                    child: GeneratedGroup53113Widget(),
                                  ),
                                  Positioned(
                                    left: 131.6669921875,
                                    top: 333.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 111.66666412353516,
                                    height: 100.0,
                                    child: GeneratedRectangle2458Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 333.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 111.66666412353516,
                                    height: 100.0,
                                    child: GeneratedRectangle2459Widget(),
                                  ),
                                  Positioned(
                                    left: 243.333984375,
                                    top: 333.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 111.66666412353516,
                                    height: 100.0,
                                    child: GeneratedRectangle2460Widget(),
                                  ),
                                  Positioned(
                                    left: 248.0390625,
                                    top: 323.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 127.58850860595703,
                                    height: 120.0,
                                    child: GeneratedRectangle2461Widget(),
                                  ),
                                  Positioned(
                                    left: 283.8818359375,
                                    top: 344.7236633300781,
                                    right: null,
                                    bottom: null,
                                    width: 46.0,
                                    height: 46.0,
                                    child: GeneratedMoving1Widget(),
                                  ),
                                  Positioned(
                                    left: 264.8330078125,
                                    top: 404.7236328125,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 19.0,
                                    child: GeneratedHomeshiftingWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 441.4476318359375,
                                    right: null,
                                    bottom: null,
                                    width: 125.0,
                                    height: 120.0,
                                    child: GeneratedRectangle2461Widget1(),
                                  ),
                                  Positioned(
                                    left: 27.0,
                                    top: 522.947509765625,
                                    right: null,
                                    bottom: null,
                                    width: 75.0,
                                    height: 22.0,
                                    child: GeneratedGardeningWidget(),
                                  ),
                                  Positioned(
                                    left: 40.0,
                                    top: 462.94757080078125,
                                    right: null,
                                    bottom: null,
                                    width: 46.0,
                                    height: 46.0,
                                    child: GeneratedGardening1Widget(),
                                  ),
                                  Positioned(
                                    left: 248.0390625,
                                    top: 441.4476318359375,
                                    right: null,
                                    bottom: null,
                                    width: 127.58850860595703,
                                    height: 120.0,
                                    child: GeneratedRectangle2461Widget2(),
                                  ),
                                  Positioned(
                                    left: 284.33331298828125,
                                    top: 522.9476318359375,
                                    right: null,
                                    bottom: null,
                                    width: 60.0,
                                    height: 22.0,
                                    child: GeneratedPaintingWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.12266666666666666;

                                      final double height =
                                          constraints.maxHeight *
                                              0.021210217200580975;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.77041796875,
                                            y: constraints.maxHeight *
                                                0.21386947103240472,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: GeneratedSurface1Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 103.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 210.22364807128906,
                                    child: GeneratedGroup53189Widget(),
                                  ),
                                  Positioned(
                                    left: 124.11328125,
                                    top: 323.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 125.0,
                                    height: 120.0,
                                    child: GeneratedRectangle2461Widget3(),
                                  ),
                                  Positioned(
                                    left: 150.11328125,
                                    top: 404.7235107421875,
                                    right: null,
                                    bottom: null,
                                    width: 78.0,
                                    height: 22.0,
                                    child: GeneratedHandymanWidget1(),
                                  ),
                                  Positioned(
                                    left: 158.88165283203125,
                                    top: 344.7236328125,
                                    right: null,
                                    bottom: null,
                                    width: 46.0,
                                    height: 46.0,
                                    child: GeneratedHandyman2Widget(),
                                  ),
                                  Positioned(
                                    left: 124.11328125,
                                    top: 441.4476318359375,
                                    right: null,
                                    bottom: null,
                                    width: 125.0,
                                    height: 120.0,
                                    child: GeneratedRectangle2461Widget4(),
                                  ),
                                  Positioned(
                                    left: 156.54296875,
                                    top: 522.947509765625,
                                    right: null,
                                    bottom: null,
                                    width: 68.0,
                                    height: 22.0,
                                    child: GeneratedDeclutterWidget1(),
                                  ),
                                  Positioned(
                                    left: 165.0,
                                    top: 462.94757080078125,
                                    right: null,
                                    bottom: null,
                                    width: 46.0,
                                    height: 46.0,
                                    child: GeneratedDeclutter2Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 589.4476318359375,
                                    right: null,
                                    bottom: null,
                                    width: 440.6968078613281,
                                    height: 166.0,
                                    child: GeneratedGroup6942Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 561.4476318359375,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 12.0,
                                    child: GeneratedRectangle222Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 779.44775390625,
                                    right: null,
                                    bottom: null,
                                    width: 440.6968078613281,
                                    height: 165.0,
                                    child: GeneratedGroup53093Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 311.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 12.0,
                                    child: GeneratedRectangle221Widget(),
                                  ),
                                  Positioned(
                                    left: 166.0,
                                    top: 296.0,
                                    right: null,
                                    bottom: null,
                                    width: 43.0,
                                    height: 7.0,
                                    child: GeneratedGroup6Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 323.2236328125,
                                    right: null,
                                    bottom: null,
                                    width: 125.0,
                                    height: 120.0,
                                    child: GeneratedRectangle2461Widget5(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 404.7236328125,
                                    right: null,
                                    bottom: null,
                                    width: 80.0,
                                    height: 22.0,
                                    child: GeneratedRenovationWidget2(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.10635109456380208;

                                      final double height =
                                          constraints.maxHeight *
                                              0.020583473892740508;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.10666666666666667,
                                            y: constraints.maxHeight *
                                                0.15955751344183025,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRenovationWidget3(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 217.84840393066406,
                                    top: 657.9594116210938,
                                    right: null,
                                    bottom: null,
                                    width: 44.0,
                                    height: 44.0,
                                    child: GeneratedImageWidget(),
                                  ),
                                  Positioned(
                                    left: 0.025390625,
                                    top: 750.22412109375,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 62.0,
                                    child: GeneratedGroup53182Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 960.44775390625,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 12.0,
                                    child: GeneratedRectangle251Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 1083.281005859375,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 12.0,
                                    child: GeneratedRectangle252Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 24.404296875,
              top: 988.44775390625,
              right: null,
              bottom: null,
              width: 328.37109375,
              height: 74.833251953125,
              child: GeneratedGroup53121Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 1508.281005859375,
              right: null,
              bottom: null,
              width: 375.0,
              height: 564.05224609375,
              child: GeneratedGroup53112Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 39.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 52.0,
              child: GeneratedGroup6823Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 39.09083938598633,
              child: GeneratediPhoneXSBarsStatusDefaultWidget(),
            ),
            Positioned(
              left: 327.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 22.0,
              height: 22.0,
              child: GeneratedSearch31Widget(),
            )
          ]),
    ));
  }
}
