import 'package:flutter/material.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedGroup52641Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedIconfinder_Arrow_Right_47818581Widget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratediPhoneXSBarsStatusDefaultWidget3.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedGroup6793Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedGroup6799Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedORCONTINUEWITHPHONENUMBERWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedGroup6796Widget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedDONTHAVEANACCOUNTSIGNUPWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginolduserswidget/generated/GeneratedRectangle210Widget3.dart';

/* Frame Login old users
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginoldusersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediPhoneXSBarsStatusDefaultWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8586666666666667;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.3149630541871921,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup6793Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8586666666666667;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.7266009852216748,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup6799Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.568;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.21866666666666668,
                        y: constraints.maxHeight * 0.1921182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWelcomeBackWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8586666666666667;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.41717980295566504,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup6796Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.364107177734375;

                  final double height =
                      constraints.maxHeight * 0.019704433497536946;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.32,
                        y: constraints.maxHeight * 0.8288174333243534,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedForgotPasswordWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7869395345052084;

                  final double height =
                      constraints.maxHeight * 0.019704433497536946;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10919791666666667,
                        y: constraints.maxHeight * 0.9014778325123153,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDONTHAVEANACCOUNTSIGNUPWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.38133333333333336;
                  double scaleX = (constraints.maxWidth * percentWidth) / 143.0;

                  double percentHeight = 0.006157635467980296;
                  double scaleY = (constraints.maxHeight * percentHeight) / 5.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.30933333333333335,
                        translateY: constraints.maxHeight * 0.9753694581280788,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine2Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08533333333333333;

                  final double height =
                      constraints.maxHeight * 0.03940886699507389;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.152,
                        y: constraints.maxHeight * 0.07635467980295567,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedIconfinder_Arrow_Right_47818581Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.744;

                  final double height =
                      constraints.maxHeight * 0.019704433497536946;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12933333333333333,
                        y: constraints.maxHeight * 0.5708128078817734,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedORCONTINUEWITHPHONENUMBERWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8586666666666667;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.068,
                        y: constraints.maxHeight * 0.6188423645320197,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle210Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7866666666666666;

                  final double height =
                      constraints.maxHeight * 0.04433497536945813;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10266666666666667,
                        y: constraints.maxHeight * 0.6360837438423645,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup52641Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
