import 'package:flutter/material.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedGroup52641Widget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedGroup6799Widget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedALREADYHAVEANACCOUNTLOGINWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedYourHomeservicesExpertWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedContinuewithPhoneNumberWidget.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedRectangle210Widget4.dart';
import 'package:flutterapp/home_20service_20appapp/generatedloginwidget/generated/GeneratedVIEWOTHEROPTIONWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8586666666666667;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.6798029556650246,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle210Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0133333333333334;

                  final double height =
                      constraints.maxHeight * 0.6022167487684729;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrameWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.76;

                  final double height =
                      constraints.maxHeight * 0.03940886699507389;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12266666666666666,
                        y: constraints.maxHeight * 0.5701970443349754,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedYourHomeservicesExpertWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.38133333333333336;
                  double scaleX = (constraints.maxWidth * percentWidth) / 143.0;

                  double percentHeight = 0.006157635467980296;
                  double scaleY = (constraints.maxHeight * percentHeight) / 5.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.30933453369140623,
                        translateY: constraints.maxHeight * 0.9766009852216748,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine2Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8586666666666667;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.7820197044334976,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup6799Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7866666666666666;

                  final double height =
                      constraints.maxHeight * 0.04433497536945813;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10666666666666667,
                        y: constraints.maxHeight * 0.6970443349753694,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup52641Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 72.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 18.0,
                child: GeneratedContinuewithPhoneNumberWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.392;

                  final double height =
                      constraints.maxHeight * 0.019704433497536946;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.30666666666666664,
                        y: constraints.maxHeight * 0.874384236453202,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedVIEWOTHEROPTIONWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7869395345052084;

                  final double height =
                      constraints.maxHeight * 0.019704433497536946;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10919791666666667,
                        y: constraints.maxHeight * 0.9273399014778325,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedALREADYHAVEANACCOUNTLOGINWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
